In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
df6 = pd.read_csv('prep0122118_train.csv')
df6.shape

(1764, 11)

In [7]:
# to fix null values
na_values = df.bedrooms.mean()

In [10]:
df.bedrooms = df.bedrooms.fillna(na_values)

In [11]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.2   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [30]:
reg_model = linear_model.LinearRegression()
reg_model.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [13]:
reg_model.coef_

array([  116.66950551, 18756.28806982, -3675.75111708])

In [14]:
reg_model.intercept_

231586.00639409182

In [15]:
reg_model.predict(df[['area','bedrooms','age']])

array([517680.56257679, 601483.40843428, 617541.31379815, 597592.55691169,
       762639.45982935, 793062.69844975])

In [17]:
reg_model.score(df[['area','bedrooms','age']],df.price)

0.9540926625396438

In [19]:
reg_model.predict([[3500,5,15]])

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([678574.44925695])

New Question


In [24]:
df1 = pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/2_linear_reg_multivariate/Exercise/hiring.csv")

In [25]:
df1

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [28]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [33]:
from word2number import w2n

In [34]:
w2n.word_to_num("five")

5

In [41]:
df1.experience = df1.experience.fillna('zero')
df1.experience = df1.experience.apply(w2n.word_to_num)

In [59]:
df1['test_score'] = df1['test_score(out of 10)'].fillna(df1['test_score(out of 10)'].median())

In [60]:
model1 = linear_model.LinearRegression()
model1.fit(df1[['experience','test_score(out of 10)','interview_score(out of 10)']],df1['salary($)'])

LinearRegression()

In [58]:
df1['test_score'] = df1['test_score(out of 10)'].fillna(df1['test_score(out of 10)'].median())

In [61]:
model1.score(df1[['experience','test_score(out of 10)','interview_score(out of 10)']],df1['salary($)'])

0.961678000257796

In [63]:
model1.predict(df1[['experience','test_score(out of 10)','interview_score(out of 10)']])

array([52350.0727802 , 45734.35225619, 58312.95487627, 63872.63464338,
       67270.74235808, 61148.47161572, 76069.1411936 , 79241.63027656])

In [64]:
model1.predict([[5,8,10]])

C:\Users\HP\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([68620.08733624])